# -*- coding: utf-8 -*-
"""KeplerLightCurves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7C-1vS2yCy14UQZhBcfeHWm6s0ZX1E0

## CSCI 8361 Lab 1: Synopsis of the Study on Kepler Light Curves Classification

[Dataset: KeplerLightCurves](https://www.timeseriesclassification.com/description.php?Dataset=KeplerLightCurves)

Install and Import
"""

#pip install -U aeon

#from aeon.datasets import load_from_ts_file
import matplotlib.pyplot as plt
import numpy as np

"""Access Datasets"""

#from google.colab import files
#uploaded1 = files.upload()  # Opens a file upload dialog box

#uploaded2 = files.upload()

# Load train and test datasets

file_path1 = "/content//KeplerLightCurves_TRAIN.ts"
kepler_TRAIN = load_from_ts_file(file_path1)

file_path2 = "/content//KeplerLightCurves_TEST.ts"
kepler_TEST = load_from_ts_file(file_path2)

"""Verify the Data"""

# Train Data
print(kepler_TRAIN[0].shape)
print(kepler_TRAIN[1].shape)

print(len(kepler_TRAIN[0]))
print(len(kepler_TRAIN))

# Test Data
print(kepler_TEST[0].shape)
print(kepler_TEST[1].shape)

print(len(kepler_TEST[0]))
print(len(kepler_TEST))

kepler_TRAIN_x=kepler_TRAIN[0]
kepler_TRAIN_lables=kepler_TRAIN[1]

kepler_TEST_x=kepler_TEST[0]
kepler_TEST_lables=kepler_TEST[1]

#print(kepler_TEST_lables)

"""**Here we can numerically visualize the 7 classes:**

1.   δ Scuti stars
2.   γ Doradus stars
3.  RR Lyrae stars
4.  Rotational variables
5.  Contact eclipsing binaries
6.  Detached eclipsing binaries
7.  Non-variable stars


"""

w = np.array(kepler_TRAIN_lables)
y = np.array(kepler_TEST_lables)
print("Original kepler_TRAIN Labels:", np.unique(w))
print("Original kepler_TEST Labels:", np.unique(y))

# kepler_TRAIN Distribution
unique_labels1, counts1 = np.unique(w, return_counts=True)

arr1 = np.array([], dtype=np.int64)
for label1, count1 in zip(unique_labels1, counts1):
    print(f"Label '{label1}' appears {count1} times.")
    arr1 = np.append(arr1, count1)

print("Total Training Instances:", np.sum(arr1))

# kepler_TEST Distribution
unique_labels, counts = np.unique(y, return_counts=True)

arr2 = np.array([], dtype=np.int64)
for label, count in zip(unique_labels, counts):
    print(f"Label '{label}' appears {count} times.")
    arr2 = np.append(arr2, count)

print("Total Test Instances:", np.sum(arr2))

#I observed class 1, 2, 3, 4, I have gotten class 2, 3, 4 right so far
label_mapping = {
    "1": "Contact Eclipsing Binary", "2": "*Detached Eclipsing Binary", "3": "*Scuti Star", "4": "*Doradus Star",
    "5": "Non-variable Star", "6": "Rotational Variable", "7": "*RR Lyrae Star"
}

w_new = np.vectorize(label_mapping.get)(w)
y_new = np.vectorize(label_mapping.get)(y)
#print("Renamed kepler_TRAIN Labels:", np.unique(w_new))
#print("Renamed kepler_TEST Labels:", np.unique(y_new))

"""Instances"""

plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[0,0,:120])
plt.title(f"Time Series Instance of Class: {y_new[0]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#Correct Guess based on single plot observation
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[70,0,:600])
plt.title(f"Time Series Instance of Class: {y_new[70]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#Correct Guess based on single plot observation
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[75,0,:1000])
plt.title(f"Time Series Instance of Class: {y_new[75]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#Correct Guess based on single plot observation
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[70,0,:5000])
plt.title(f"Time Series Instance of Class: {y_new[70]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[500,0,:2000])
plt.title(f"Time Series Instance of Class: {y_new[500]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#Correct Guess based on single plot observation
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[280,0,:2000], color="green")
plt.title(f"Time Series Instance of Class: {y_new[280]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[800,0,:2000], color="purple")
plt.title(f"Time Series Instance of Class: {y_new[800]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#Correct Guess for 4 and 2 based on comparison plot (Contact EB's fluctuations are larger than mostly all; you also see the classic pattern of a doradus star)
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[160,0,:2000], label=f"Instance 160: {y_new[160]}")
plt.plot(kepler_TEST_x[10,0,:2000], label=f"Instance 10: {y_new[10]}")
plt.plot(kepler_TEST_x[500,0,:2000], label=f"Instance 500: {y_new[500]}")
plt.legend()
plt.title(f"Time Series Class Instance: {y_new[10]}, {y_new[160]}, and {y_new[500]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")

#In this comparison plot, you can see the classification characteristics of the RR Lyrae Star more clearly (class 1 vs class 7).
plt.figure(figsize=(20,5))
plt.plot(kepler_TEST_x[10,0,:2000], label=f"Instance 10: {y_new[10]}")
#plt.plot(kepler_TEST_x[160,0,:2000], label=f"Instance 160: {y_new[160]}")
#plt.plot(kepler_TEST_x[200,0,:2000], label=f"Instance 200: {y_new[200]}")
#plt.plot(kepler_TEST_x[500,0,:2000], label=f"Instance 500: {y_new[500]}")
#plt.plot(kepler_TEST_x[700,0,:2000], label=f"Instance 700: {y_new[700]}")
#plt.plot(kepler_TEST_x[800,0,:2000], label=f"Instance 800: {y_new[800]}")
plt.plot(kepler_TEST_x[910,0,:2000], label=f"Instance 700: {y_new[910]}")
plt.legend()
plt.title(f"Time Series Class Instance: {y_new[10]} and {y_new[910]}")
plt.xlabel("Time")
plt.ylabel("Long-cadence Photometry")
